### PR TITLE
feat: add python script for automation

### PR DESCRIPTION
**Pull request by npv12**

### CODE REVIEW

**Comment by npv12** [comment]
Some of the colors especially latte are still not perfect and needs tweaking

**Comment by npv12** [comment]
Latte still has some visibility issues with text but everything else should be done. I really need help with fixing latte bugs

**Comment by npv12** [comment]
latte issues should be fixed now

**Comment by ghostx31** [comment]
Tested this. Looks great to me! Thanks for the PR.

**Pull request merged**
