### PR TITLE
fix: alt tab menu

### LINKED ISSUE #177: App switcher not fully using theme coloring
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe the bug.

The app switcher that usually pops up when you press ALT + TAB still has traces of the default gnome theme coloring

### Attach screenshots.

https://github.com/catppuccin/gtk/assets/37044906/cff7a028-0ce6-47b7-b7fd-448ce6766961

### How did you install the theme?

From source (Python script)

### If using GTK4, have you symlinked the "gtk-4.0" folder?

- [X] I have symlinked the `gtk-4.0` folder.

### What GNOME version are you seeing the bug on?

GNOME Version 46.1

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by nullishamy**
Closes #177

### CODE REVIEW

**Comment by nullishamy** [comment]
We still need to figure out what the best approach to upstreaming these patches is. Let's label it for now so we can revisit it in the future.

**Comment by isabelroses** [comment]
> We still need to figure out what the best approach to upstreaming these patches is. Let's label it for now so we can revisit it in the future.

I think add the patch, such that anyone running the repo from main is happy. Then also upstream the patch, and remove the patch when its merged.

**Comment by isabelroses** [comment]
> Should we make a secondary issue to track the upstream contribution? 

Seems like a good idea to me.

> I don't think we should block our patch PRs on someone contributing it upstream?

I assume this means anyone can contribute here or upstream? If so, we should mark PRs that are considered upstream patches and send it up ourselves, that should prevent us blocking PRs to this repo.

**Comment by isabelroses** [comment]
> > I assume this means anyone can contribute here or upstream? If so, we should mark PRs that are considered upstream patches and send it up ourselves, that should prevent us blocking PRs to this repo.
> 
> I don't see why not! If we have the patch files, anyone can submit the PR upstream. Should make some labels to describe this, and have some instructions in the CONTRIBUTING?

seems good to me.

**Comment by nullishamy** [comment]
Blocked on v1.

**Review by sgoudham — APPROVED** [review]

**Pull request merged**
